config/routes.rb
Rails.application.routes.draw do

# user and posts resources
  resources :users
  resources :posts
  resources :comments

# landing page, link to about page, sign up, sign in buttons
  root 'home#index'
  get '/about' => 'home#about'

# user sign up / delete account routes
  get '/goodbye' => 'users#goodbye'

# user login / logout routes
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/login_error' => 'sessions#login_error'
  delete '/logout' => 'sessions#destroy'
  get '/logout' => 'sessions#logged_out'

# user dashboard and manage account
  get '/dashboard' => 'users#dashboard'
  get '/manage' => 'users#manage'
  post '/manage' => 'users#update'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  validates :username, uniqueness: true
  validates :email, uniqueness: true
  validates_presence_of :fname, :username, :email, :password
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  include SessionsHelper
  include UsersHelper
  include PostsHelper
  include CommentsHelper

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    puts params.inspect
    write_comment
  end

  def index
    @comments = Comment.all.order("created_at DESC")
  end

  def show
    @comment = Comment.find(params[:id])
    @post = @comment.post
  end

  def update
    edit_comment
  end

  def edit
    @comment = Comment.find(params[:id])
    @post = @comment.post
  end

  def destroy
    delete_comment
    redirect_to user_post_path
  end

  private

  def comment_params
    params.require(:comment).permit(:comment, :post_id)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
  end

  def about
  end

  def posts
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all.order("created_at DESC")
  end

  def show
    @post = Post.find(params[:id])
    @user = @post.user
    @comments = Comment.where({ post_id: @post })
  end

  def new
    @post = Post.new
  end

  def create
    puts params.inspect
    write_post
  end

  def update
    edit_post
  end

  def destroy
    delete_post
    redirect_to user_post_path
  end

  # private methods
    private

    def post_params
      params.require(:post).permit(:message)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    puts params.inspect
    @user = User.find_by(username: params[:session][:username])
    if @user && @user.authenticate(params[:session][:password])
        log_in(@user)
        redirect_to dashboard_path @user
      else
        redirect_to login_error_path
      end
  end

  def destroy
    log_out
    redirect_to logout_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    current_user
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    puts params.inspect
    @user = User.create(user_params)
      if @user.save
        log_in(@user)
        redirect_to dashboard_path @user
      else
        render 'new'
      end
  end

  def show
    @user = User.find(params[:id])
    @post = Post.new
    @posts = @user.posts.all.order("created_at DESC")
    @comment = Comment.new
  end

  def dashboard
    @user = User.find(session[:user_id])
    @post = Post.new
    @posts = Post.all.order("created_at DESC")
  end

  def manage
    @user = User.find(session[:user_id])
  end

  def edit
    @user = User.find(session[:user_id])
  end

  def update
    user = User.find(session[:user_id])
    user.update(user_params)
    redirect_to user_path
  end

  def destroy
    delete_user
    redirect_to goodbye_path
  end

  def goodbye
  end

  # private methods
    private

    def user_params
      params.require(:user).permit(:fname, :lname, :username, :email, :password)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_user
    @current_user ||= User.find_by(session[:user_id])
  end
  
end

app/helpers/comments_helper.rb
module CommentsHelper

  def write_comment
    @comment = Comment.new(comment_params)
    @comment.user_id = session[:user_id]
    if @comment.save
      redirect_to posts_path
    else
      p 'ERRORS:'
      p @comment.errors.full_messages
      render 'index'
    end
  end

  def edit_comment
    @comment = Comment.find(params[:id])
      if @comment.update(comment_params)
        redirect_to dashboard_path(User.find(session[:user_id]))
      else
        render 'show'
      end
  end

  def delete_comment
    @comment = Comment.find(params[:id])
    @comment.destroy
  end

end

app/helpers/posts_helper.rb
module PostsHelper

  def write_post
    @post = Post.new(post_params)
    @post.user_id = session[:user_id]
    if @post.save
      redirect_to dashboard_path(User.find(session[:user_id]))
    else
      render 'index'
    end
  end

  def edit_post
    @post = Post.find(params[:id])
      if @post.update(post_params)
        redirect_to dashboard_path(User.find(session[:user_id]))
      else
        render 'show'
      end
  end

  def delete_post
    @post = Post.find(params[:id])
    @post.destroy
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find(session[:user_id])
  end

  def log_out
    reset_session
    @current_user = nil
  end

end

app/helpers/users_helper.rb
module UsersHelper

  def user_welcome
     if @user != nil
        content_tag :h1, "hi, #{@user.username}!"
     end
  end

  def user_profile
     if @user != nil
        content_tag :h1, "#{@user.username}"
     end
  end

  def user_since
     if @user != nil
        content_tag :h4, "phluxn around for #{time_ago_in_words(@user.created_at)}"
     end
  end

  def delete_user
    @delete_account = User.find(session[:user_id]).destroy
    session[:user_id] = nil
  end

end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/comments/index.html.erb
<h1> comments </h1>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>

app/views/comments/update.html.erb
<h1>Comments#update</h1>
<p>Find me in app/views/comments/update.html.erb</p>

app/views/home/about.html.erb
<div>

  <p>
    i want phlux to be where you go to feel connected.
  </p>

  <p>
    find out about shows, catch up with friends, make plans, meet for drinks first, split a car to get there.
  </p>

  <p>
    the idea for phlux was inspired, in part, by a group-text i'm in. we're just a bunch of pals who hang out and go to shows.
  </p>

  <p>
    i see phlux like that, but bigger, better, for everyone. the group-text of the philly music scene.
  </p>

  <h1> join <a href="/"> phlux </a> today. </h1>

  <p>
    i'll be working to make this app better all the time. i want it to be useful. fun and easy to use. and the best way to know how i'm doing is to hear from you: the community that uses it. if there are ways you think this app could be improved (visually, functionally, etc.) please
    <a href="mailto: allegra.anka@gmail.com">let me know!</a>
  </p>

</div>

app/views/home/index.html.erb
<div>
  <p>
    your place for philly shows
  </p>
</div>

<nav>
  <ul class="index_buttons">
    <li> <div> <%= link_to("get started", new_user_path, method: :get) %> </div> </li>
    <li> <div> <%= link_to("log in", login_path, method: :get) %> </div> </li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhluxShows</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Didact+Gothic|Roboto" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="header">
      <h1 class="logo animated flip"> <a href="/">phlux</a> </h1>
    </div>

    <div class="yield-div">
      <%= yield %>
      <% debug(params) if Rails.env.development? %>
    </div>

    <div class="footer">
      <ul>
        <li> &copy 2018 <strong>phlux</strong> | </li>
        <li> <%= link_to("about", about_path, method: :get) %> </li>
        <li> <%= link_to("terms", about_path, method: :get) %> </li>
        <li> <%= link_to("privacy", about_path, method: :get) %> </li>
      </ul>
    </div>

  </body>
</html>

app/views/posts/index.html.erb
<div> <%= link_to("<< back to dashboard", dashboard_path, :class => 'back-link') %> </div>

<div>
  <ul class="post_index_display">
    <% @posts.each do |post| %>
      <li> <span class="username_display"> <%= post.user.username %>: </span> <%= post.message %> </li>
    <% end %>
  </ul>
</div>

app/views/posts/show.html.erb
<div> <%= link_to("<< back to profile", user_path(@user), :class => 'back-link') %> </div>

<h1> post thread </h1>
<div class="single_post_container">
  <div class="single_post">
    <span class="username_display"> <%= @user.username %>: </span>
    <p>
      <%= @post.message %>
    </p>
  </div>
</div>

<div>
  <h1> comments </h1>
    <% @comments.each do |comment| %>
      <div> <%= comment.user.username %>: <%= comment.comment %> </div>
    <% end %>
</div>

app/views/users/dashboard.html.erb
  <div class="dash_nav">
    <ul>
      <li>
        <%= link_to("see who's on phlux", users_path, method: :get) %>
      </li>
      <li>
        <%= link_to("my profile", user_path(@user), method: :get) %>
      </li>
      <li>
        <%= link_to("manage account", manage_path(@user), method: :get) %>
      </li>
      <li>
        <%= link_to("thread", posts_path, method: :get) %>
      </li>
    </ul>
    <div class="header_items">
        <%= form_tag("/search", method:"get") do %>
          <%= label_tag(:query, "search phlux:") %>
          <%= text_field_tag(:query) %>
          <%= submit_tag("search") %>
        <% end %>
    </div>
  </div>

  <div class="welcome">
    <%= user_welcome %>
  </div>

  <h3> what's happening? </h3>
  <div>
    <%= form_for @post do |f| %>
        <div>
          <%= f.text_field :message, placeholder: "post to phlux" %>
        </div>
        <div>
          <%= f.submit "post" %>
        </div>
    <% end %>
  </div>
</div>

<div class="scroll">
  <ul class="post_index_display">
    <% @posts.each do |post| %>
      <li>
        <div class="chatbox_posts">
          <span class="username_display"> <%= post.user.username %>: </span> <%= post.message %>
        </div>
      </li>
    <% end %>
  </ul>
</div>

<h3> <%= link_to("log out", logout_path, method: :delete) %> </h3>

<div class="user_since"> <%= user_since %> </div>

app/views/users/edit.html.erb
<div> <%= link_to("<< back to dashboard", dashboard_path) %> </div>
<div> <%= link_to("<< back to manage account", manage_path, :class => 'back-link') %> </div>

<h1> edit account details </h1>
<p>replace what you want to change, enter your password, and submit!</p>

<%= form_for @user do |f| %>
  <div>
    <%= f.text_field :fname, placeholder: "First Name" %>
  </div>

  <div>
    <%= f.text_field :lname, placeholder: "Last Name" %>
  </div>

  <div>
    <%= f.text_field :username, placeholder: "Username" %>
  </div>

  <div>
    <%= f.text_field :email, placeholder: "Email" %>
  </div>

  <div>
    <%= f.password_field :password, placeholder: "Password" %>
  </div>

  <div>
    <%= f.submit "edit account" %>
  </div>
<% end %>

app/views/users/goodbye.html.erb
<h1> sorry to see you go! maybe we'll see you at a show? </h1>

<p> return <%= link_to("home", root_path, method: :get) %> </p>

app/views/users/index.html.erb
<div> <%= link_to("<< back to dashboard", dashboard_path, :class => 'back-link') %> </div>

<div>
  <h1>
    phlux users
  </h1>
</div>

<% @users.each do |user| %>
  <p> <%= link_to(user.username, user_path(user), method: :get) %> </p>
<% end %>

app/views/users/manage.html.erb
<div> <%= link_to("<< back to dashboard", dashboard_path, :class => 'back-link') %> </div>

<div class="manage_account">
  <ul>
    <li> <h1> manage account </h1> </li>
    <li> <%= link_to("edit account", edit_user_path(@user), method: :get) %> </li>
    <li> <%= link_to("delete account", user_path(@user), method: :delete) %> </li>
  </ul>
</div>

app/views/users/new.html.erb
<h1> create an account </h1>

<%= form_for @user do |f| %>
  <div>
    <%= f.text_field :fname, placeholder: "First Name" %>
  </div>

  <div>
    <%= f.text_field :lname, placeholder: "Last Name" %>
  </div>

  <div>
    <%= f.text_field :username, placeholder: "Username" %>
  </div>

  <div>
    <%= f.text_field :email, placeholder: "Email" %>
  </div>

  <div>
    <%= f.password_field :password, placeholder: "Password" %>
  </div>

  <div>
    <%= f.submit "create account" %>
  </div>
<% end %>

app/views/users/show.html.erb
<div> <%= link_to("<< back to dashboard", dashboard_path, :class => 'back-link') %> </div>
<div> <%= link_to("<< back to users", users_path, method: :get) %> </div>

<h1> <%= user_profile %> </h1>

<div>
  <ul class="post_index_display post_profile_display">
    <li> <span class="username_display"> <%= @user.username %></span>'s posts</li>
    <% @posts.each do |post| %>
      <li>
        <a href="/posts/<%= post.id %>">
          <div class="profile_posts">
           <%= post.message %>
          </div>
        </a>
        <div>
          <%= form_for @comment do |f| %>
              <div>
                <%= hidden_field_tag 'comment[post_id]', post.id %>
                <%= f.text_field :comment, placeholder: "comment" %>
                <%= f.submit "post" %>
              </div>
          <% end %>
        </div>
      </li>
    <% end %>
  </ul>
</div>